thefarmalp:
  build: .
  volumes:
    - .:/thefarmalp
  ports:
    - '3000:3000'
  env_file:
    - .thefarmalp.env
    
#postgres:
#  image: postgres:9.4.5
#  environment:
#    POSTGRES_USER: drkiq
#    POSTGRES_PASSWORD: yourpassword
#  ports:
#    - '5432:5432'
#  volumes:
#    - drkiq-postgres:/var/lib/postgresql/data

#redis:
#  image: redis:3.0.5
#  ports:
#    - '6379:6379'
#  volumes:
#    - drkiq-redis:/var/lib/redis/data